In [9]:
import datetime
import itertools
import matplotlib.pylab as plt
import numpy as np
import pandas as pd
import random
import pickle
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.model_selection import KFold
import torch
from tqdm import tqdm
from sklearn import preprocessing
# NLP
from sklearn.decomposition import PCA
import transformers
import ssl

In [10]:
df = pd.read_csv('/content/train.csv')

In [11]:
df.head()


LOAN_ID ORIGINAL_LANGUAGE  ... REPAYMENT_INTERVAL DISTRIBUTION_MODEL
0  1733169           English  ...            monthly      field_partner
1  1546998           English  ...            monthly      field_partner
2  1808517           Spanish  ...             bullet      field_partner
3  1452940           English  ...            monthly      field_partner
4  1778420           English  ...             bullet      field_partner

[5 rows x 18 columns]

## BERT for Description Translated

In [12]:
description = df[['DESCRIPTION_TRANSLATED']]
description

DESCRIPTION_TRANSLATED
0      Teodora is a 50-year-old married woman from th...
1      Diego is 32 years old and lives in the municip...
2      Osman is a young man, 27 years old, single, an...
3      His name is Nino, 31 years old, married to Che...
4      Pictured above is Teresa, often described as a...
...                                                  ...
91328  Rider is 20 years old. He lives in San Javier,...
91329  Carmelita works hard to support four children....
91330  Orn, 60 years of age, appears in the photo. Sh...
91331  At 27 years of age, Walter is in a live-in rel...
91332  Greetings from Uganda! This is Godfrey. He is ...

[91333 rows x 1 columns]

In [13]:
import re
def cleaning(text):
    text = re.sub("\n", " ", text) 
    text = re.sub("[^A-Za-z0-9]", " ", text) 
    text = re.sub("[' ']+", " ", text) 
    return text.lower() 

Creating a class for BERT 

In [14]:
import torch
import transformers

from transformers import BertTokenizer


class BertSequenceVectorizer:
    def __init__(self, model_name="bert-base-uncased", max_len=128):
        self.device = "cuda" if torch.cuda.is_available() else "cpu"
        self.model_name = model_name
        self.tokenizer = BertTokenizer.from_pretrained(self.model_name)
        self.bert_model = transformers.BertModel.from_pretrained(self.model_name)
        self.bert_model = self.bert_model.to(self.device)
        self.max_len = max_len

    def vectorize(self, sentence: str) -> np.array:
        inp = self.tokenizer.encode(sentence)
        len_inp = len(inp)

        if len_inp >= self.max_len:
            inputs = inp[:self.max_len]
            masks = [1] * self.max_len
        else:
            inputs = inp + [0] * (self.max_len - len_inp)
            masks = [1] * len_inp + [0] * (self.max_len - len_inp)

        inputs_tensor = torch.tensor([inputs], dtype=torch.long).to(self.device)
        masks_tensor = torch.tensor([masks], dtype=torch.long).to(self.device)

        bert_out = self.bert_model(inputs_tensor, masks_tensor)
        seq_out, pooled_out = bert_out['last_hidden_state'], bert_out['pooler_output']

        if torch.cuda.is_available():    
            return seq_out[0][0].cpu().detach().numpy() # 0番目は [CLS] token, 768 dim の文章特徴量
        else:
            return seq_out[0][0].detach().numpy()

In [15]:
BSV = BertSequenceVectorizer(
    model_name="bert-base-uncased",
    max_len=128)
features = np.stack(
    description["DESCRIPTION_TRANSLATED"].fillna("").map(lambda x: BSV.vectorize(x).reshape(-1)).values
)
features

Downloading:   0%|          | 0.00/226k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/28.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/455k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/570 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/420M [00:00<?, ?B/s]

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.bias', 'cls.predictions.decoder.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Token indices sequence length is longer than the specified maximum sequence length for this model (570 > 512). Running this sequence through the model will

array([[-0.24173544, -0.4984473 ,  0.5118569 , ..., -0.26480898,
         0.09317772,  0.08919012],
       [-0.21131033, -0.1476567 ,  0.5652367 , ..., -0.45297495,
         0.62749416,  0.16616036],
       [-0.2587864 ,  0.18665488,  0.26470667, ..., -0.42402166,
         0.33215922,  0.09634593],
       ...,
       [-0.12291255, -0.2524864 ,  0.04267163, ...,  0.04285635,
         0.2550213 , -0.03334789],
       [-0.12975581, -0.24003473,  0.39712143, ..., -0.15320235,
         0.17523946,  0.12909105],
       [ 0.08368339, -0.18113215, -0.04754119, ...,  0.06178788,
        -0.00276763,  0.7165465 ]], dtype=float32)

In [16]:
features.shape

(91333, 768)

In [17]:
train_description = pd.DataFrame(features)

Although the data tends to be huge and we do not want to use everything, we want to represent a multivariate data table as smaller set of variables (summary indices) in order to observe trends, jumps, clusters and outliers. In order to archive this, PCA will be implemented.

In [18]:
pca = PCA(n_components=0.80,random_state=42)
pca.fit_transform(train_description)
print(pca.explained_variance_ratio_)
print('Cumulative principal variance : ', np.sum(pca.explained_variance_ratio_)) 
print('The number of principal components: ', pca.n_components_) 

[0.39623847 0.05335096 0.04748863 0.02975008 0.0251465  0.02147628
 0.01842006 0.01704253 0.01324411 0.01205773 0.01134471 0.01039008
 0.00907982 0.00848714 0.00814909 0.00755839 0.00691977 0.0065606
 0.00638777 0.00576017 0.00560995 0.00523428 0.00495519 0.00491989
 0.0046147  0.00438272 0.00418341 0.004085   0.00390139 0.00379354
 0.00369959 0.00350213 0.00345559 0.00329167 0.00316319 0.00307948
 0.0030113  0.00282294 0.0027719  0.00271122 0.00262791 0.00254488
 0.00248884 0.00245975]
Cumulative principal variance :  0.8021633657635638
The number of principal components:  44


In [19]:
text_vec = pca.fit_transform(train_description)
output_df = pd.DataFrame(text_vec, columns=[f'bert_pca_vecs={i:03}' for i in range(text_vec.shape[1])])

In [20]:
output_df.head()

bert_pca_vecs=000  bert_pca_vecs=001  ...  bert_pca_vecs=042  bert_pca_vecs=043
0          -4.328352           0.546912  ...          -0.267159          -0.414777
1          -4.699850           0.686877  ...          -0.294301           0.293447
2          -5.302714           0.922105  ...          -0.080489          -0.147476
3          -4.488940           0.777891  ...          -0.679150           0.011661
4          -3.044583          -0.961134  ...          -0.021726          -0.681904

[5 rows x 44 columns]

Same Process for the test data

In [21]:
test = pd.read_csv('/content/test.csv')

In [22]:
test_description = test[['DESCRIPTION_TRANSLATED']]

In [23]:
test_description

DESCRIPTION_TRANSLATED
0      Marcela is 69 years old and married with ten c...
1      Roselia is 48 years old and has five children....
2      Ma. Marebil is a single woman, 40 years old wi...
3      Good day, lenders! Meet one of KBMI’s clients,...
4      Rosemarie is a married woman with two children...
...                                                  ...
91817  Marjorie is a resident of Tubigon, Bohol. She ...
91818  Hello, Kiva community! Meet Janeth, a mother e...
91819  Komi is 32 years old and married. He is a reno...
91820  Kalbubu is 56 years old, a widow, and she has ...
91821  Hinrilyn is 31 years old and has two children....

[91822 rows x 1 columns]

Error: Runtime no longer has a reference to this dataframe, please re-run this cell and try again.


In [24]:
BSV = BertSequenceVectorizer(
    model_name="bert-base-uncased",
    max_len=128)
features_test = np.stack(
    test["DESCRIPTION_TRANSLATED"].fillna("").map(lambda x: BSV.vectorize(x).reshape(-1)).values
)
features_test

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.bias', 'cls.predictions.decoder.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Token indices sequence length is longer than the specified maximum sequence length for this model (515 > 512). Running this sequence through the model will

array([[-0.02162604, -0.2814147 ,  0.13555394, ..., -0.33768883,
         0.11497159,  0.11687837],
       [ 0.05312145, -0.7417049 ,  0.21979214, ..., -0.59250534,
         0.1289405 ,  0.31543347],
       [ 0.06533924, -0.14293553, -0.149278  , ..., -0.27435064,
        -0.00088617,  0.07431131],
       ...,
       [-0.45251736,  0.05666868,  0.08293466, ..., -0.15872467,
         0.3543674 ,  0.39797008],
       [-0.11534022, -0.3343771 , -0.02148527, ...,  0.09149812,
         0.4145456 ,  0.3540789 ],
       [-0.06062814, -0.41311967, -0.1160955 , ..., -0.32696483,
         0.14316198, -0.03807072]], dtype=float32)

In [25]:
features_test.shape

(91822, 768)

In [26]:
test_description = pd.DataFrame(features_test)

In [27]:
test_text_vec = pca.transform(test_description)
output_test = pd.DataFrame(test_text_vec, columns=[f'bert_pca_vecs={i:03}' for i in range(test_text_vec.shape[1])])

In [28]:
output_test.head()

bert_pca_vecs=000  bert_pca_vecs=001  ...  bert_pca_vecs=042  bert_pca_vecs=043
0           6.170295          -0.690748  ...           0.023095           0.019331
1          -3.255446          -0.283549  ...          -0.464946          -0.221054
2           6.610266          -0.797629  ...          -0.370217          -0.119013
3          -2.281190          -0.358886  ...           0.428985           0.527931
4           6.225177          -1.270165  ...           0.002951           0.032612

[5 rows x 44 columns]

In [29]:
output_df.to_csv('translated_df.csv',index=False)
output_test.to_csv('translated_test.csv',index=False)

## BERT for Loan use

In [32]:
df = pd.read_csv('/content/train.csv')
loan_use = df[['LOAN_USE']]

In [33]:
loan_use.head()

LOAN_USE
0  to purchase  materials like nipa palm, bamboo ...
1  to buy two hair clippers, a new barber chair, ...
2  to purchase sacks of fertilizers to care for a...
3  to pay for fuel, tires and change oil for his ...
4  to purchase hybrid seeds and fertilizer to imp...

In [34]:
loan_use.isnull().sum()

LOAN_USE    0
dtype: int64

In [36]:
BSV = BertSequenceVectorizer(
    model_name="bert-base-uncased",
    max_len=128)
features_loan = np.stack(
    loan_use["LOAN_USE"].fillna("").map(lambda x: BSV.vectorize(x).reshape(-1)).values
)
features_loan

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.bias', 'cls.predictions.decoder.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


array([[-0.42625305, -0.18134747, -0.5691531 , ..., -0.35933882,
        -0.01911237,  0.20568702],
       [-0.18472293,  0.14233777, -0.4939079 , ..., -0.01785411,
         0.31023964,  0.41539967],
       [-0.69709086,  0.00822136, -0.69294524, ...,  0.07566786,
         0.2995988 ,  0.62147367],
       ...,
       [-0.1269912 ,  0.16883278, -0.3274002 , ...,  0.0737204 ,
        -0.12253695,  0.28383365],
       [-0.41563365,  0.38399398, -0.7371895 , ..., -0.3353454 ,
         0.66786915,  0.38453695],
       [-0.6315305 ,  0.01077621, -0.06907047, ..., -0.11072415,
         0.24069753,  0.7386902 ]], dtype=float32)

In [37]:
features_loan.shape

(91333, 768)

In [38]:
train_loan = pd.DataFrame(features_loan)

In [39]:
pca = PCA(n_components=0.70,random_state=42)
pca.fit_transform(train_loan)
print(pca.explained_variance_ratio_)
print('Cumulative principal variance : ', np.sum(pca.explained_variance_ratio_)) 
print('The number of principal components: ', pca.n_components_) 

[0.19791166 0.09294052 0.06528146 0.05184975 0.0413109  0.03365116
 0.02788574 0.02556001 0.02139069 0.01980715 0.01884646 0.01620687
 0.01518014 0.01364982 0.0127708  0.01165373 0.01057499 0.00956617
 0.00902119 0.00841581]
Cumulative principal variance :  0.7034750148691867
The number of principal components:  20


In [40]:
text_vec = pca.fit_transform(train_loan)
output_df_loan = pd.DataFrame(text_vec, columns=[f'bert_pca_vecs={i:03}' for i in range(text_vec.shape[1])])

In [41]:
output_df_loan.head()

bert_pca_vecs=000  bert_pca_vecs=001  ...  bert_pca_vecs=018  bert_pca_vecs=019
0          -1.873963          -4.209408  ...          -0.099085           0.372613
1          -2.106485           1.533609  ...           0.459440          -0.153268
2           4.581669          -0.668851  ...           1.027182           0.033943
3          -2.962453          -0.123048  ...          -0.499021           0.301853
4           1.680044          -4.007218  ...           0.554334          -0.943748

[5 rows x 20 columns]

In [42]:
test_loan_use = test[['LOAN_USE']]

In [43]:
BSV = BertSequenceVectorizer(
    model_name="bert-base-uncased",
    max_len=128)
features_test_loan = np.stack(
    test_loan_use["LOAN_USE"].fillna("").map(lambda x: BSV.vectorize(x).reshape(-1)).values
)
features_test_loan

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.bias', 'cls.predictions.decoder.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


array([[-0.15475358, -0.22458985, -0.7245282 , ..., -0.07552186,
         0.22399327,  0.32503837],
       [-0.26769018, -0.0563505 , -0.45401907, ..., -0.2470951 ,
         0.14184983,  0.3993165 ],
       [-0.2690688 , -0.09582914, -0.4195484 , ..., -0.22475171,
        -0.08977056,  0.4331357 ],
       ...,
       [-0.36572364, -0.11463489, -0.67984647, ..., -0.00687652,
         0.21289454,  0.648167  ],
       [-0.22462344, -0.33622926, -0.7478062 , ..., -0.00740216,
         0.10952365,  0.4831206 ],
       [-0.32016847, -0.17805609, -0.6668866 , ..., -0.29715493,
         0.30646473,  0.27811107]], dtype=float32)

In [44]:
features_test_loan.shape

(91822, 768)

In [45]:
test_loan = pd.DataFrame(features_test_loan)

In [46]:
test_text_vec = pca.transform(test_loan)
output_test_loan = pd.DataFrame(test_text_vec, columns=[f'bert_pca_vecs={i:03}' for i in range(test_text_vec.shape[1])])

In [47]:
output_test_loan.head()

bert_pca_vecs=000  bert_pca_vecs=001  ...  bert_pca_vecs=018  bert_pca_vecs=019
0           1.464348           2.054109  ...           0.411929          -0.211481
1          -2.604720          -1.101160  ...          -0.446153           0.721414
2          -1.023414           2.061169  ...          -0.536992           0.080827
3          -0.859172           4.013445  ...          -0.365589          -0.824010
4          -5.878501          -0.574069  ...           0.097553           0.453247

[5 rows x 20 columns]

In [48]:
output_df_loan.to_csv('loan_use_df.csv',index=False)
output_test_loan.to_csv('loan_use_test.csv',index=False)